const ADD_MOVIES = 'ADD_MOVIES';
const REMOVE_MOVIES = 'REMOVE_MOVIES';

const SET_FILTER = 'SET_FILTER';
const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
const INCREASE_PAGE = 'INCREASE_PAGE';
const DECREASE_PAGE = 'DECREASE_PAGE';

export {
  ADD_MOVIES,
  REMOVE_MOVIES,
  SET_FILTER,
  SET_TOTAL_PAGES,
  INCREASE_PAGE,
  DECREASE_PAGE,
};
